services:
   database_mysql:
     image: mysql:8.3.0
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - database_mysql
     image: wordpress:6.5.2
     ports:
       - "8888:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: database_mysql:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data: