services:
  jira:
    container_name: jira
    image: atlassian/jira-software:9.12
    ports:
      - "8000:8080"
    volumes:
      - jira_data:/var/atlassian/application-data/jira
  jira_db:
    image: postgres:15-alpine
    container_name: jira_db #FIXME

volumes:
  jira_data: